### ISSUE TITLE
Instructions in the readme on how to use on MacOS & Linux?

### ISSUE THREAD

**Issue by khalilgharbaoui** [DevL0rd/SkyNX#1]

**Comment by DevL0rd** [comment]
It won't work on mac os or linux just yet. Though it should be easy to port soon. I don't have a mac either. But if you want I can send you test builds for mac when I start on it!

**Comment by khalilgharbaoui** [comment]
@DevL0rd Well I'm in the no-windows-land and have plenty of macs laying around.  
I'll gladly test those build out for you to help accelerate mac support.
I can also build the streamer from source if needed. You just let me know. 💪

**Comment by DevL0rd** [comment]
I don't see the streaming part being an issue, as long as you can get ffmpeg binarys for mac.
But I do think emulating a controller is going to take me a minute to research. I have a few more bugs to iron out, but I will message you back here sometime with a test version.

**Comment by khalilgharbaoui** [comment]
sure.

**Comment by knives-repo** [comment]
Are there still test versions of this for Mac?
