### ISSUE TITLE
PC Side Server throws "Java Exception"

### ISSUE THREAD

**Issue by Ry3yr** [DevL0rd/SkyNX#10]
OS: Win 7 (x64) [Firewall for test: off (albeit SkyNX was added to the exception list)]
Switch: Atmosphere, FW: 10.0

Driver installation seemed to work afaik.

(#Note: For some outlandish reason, it *somewhat* works on my Win 10, but throws an error on exit [https://i.imgur.com/6QnIYRF.png])

Error is as follows
![Screenshot_2020-04-25-19-23-19](https://user-images.githubusercontent.com/17431197/80286239-78021500-872a-11ea-9182-eb98f5d0db9a.jpg)

**Comment by DevL0rd** [comment]
You are missing all the files that came with the EXE

**Comment by Ry3yr** [comment]
Ha!
Seems I had to change the symlinks folder to be "executed in" precisely SkyNX's.

What a foolish error of mine.

Thanks :)

**Comment by DevL0rd** [comment]
Np!
