### ISSUE TITLE
Absolutely no stable 60fps, even if stats say it is

### ISSUE THREAD

**Issue by oocyberkevinoo** [DevL0rd/SkyNX#11]
Well, yeah, it just don't run well at all, render are sometimes at 60fps for not even a second, then 30 or less, completely unstable

Switch is connected to 5Ghz wifi network, and PC to Ethernet 1Gbps

**Comment by campofmusic** [comment]
100%, says on the program that i have 60FPS but no 60 in realtime.
i have RTX 2070 with ryzen 2600X and 16RAM.

20mb's works no problem but i see lower than 20fps maybe 10-15, 4mbps will give me more close to 30.

no 60 at all!

**Comment by dukemagus** [comment]
change the desktop resolution to 1280x720 and see if it improves anything

**Comment by oocyberkevinoo** [comment]
I'm already in 1280x720, no differences :/
Also, I'm using an RTX2060, i7 3770k, 16Go Ram DDR3, SSD 860Evo 1To

Wifi is high quality and I'm near it, and Ethernet is a perfect 1Gbps connection Fullduplex, there's no connection issue, so I assume it's something with RTX that have issue ?

**Comment by DevL0rd** [comment]
I spose i made the fps counter measer the stream rate not the recieve lol oops.

Waht firmware version are you guys on, and what cfw?

**Comment by oocyberkevinoo** [comment]
I'm on Atmosphere 0.10.x (don't have my switch to check better) and OS 9.1.0

**Comment by DevL0rd** [comment]
It is real analog control :)

**Comment by DevL0rd** [comment]
Odd question. It works really well for most. And your systems can clearly handle it. Have you tried restarting your router? or the switch?

The switch app is the most consistent part, everyones switch is basically the same.
But for windows, ehh. Who knows lol.
I'm adding a nvidia encoder soon so that will speed things up.

But what is your cpu usage like? And is the game you are playing fullscreened or borderless?

**Comment by dukemagus** [comment]
The last suspect in this would be ffmpeg doing something dumb on the screen capture and conversion before streaming it to switch.

**Comment by DevL0rd** [comment]
I agree. It is possible it's a weird ffmpeg thing. But when I put out nvenc you should try it out and see if it works better. I will have to do some research to see if amd has a encoder for their GPUs

**Comment by oocyberkevinoo** [comment]
My router reboot some days ago, I'm pretty sure this is not the issue here :/

The Switch was just booted in EmuMMC before trying the homebrew :/
Windows just rebooted after drivers install of your software too..

Also, to me I'm 100% sure that the analog output just 8 directions :/

**Comment by Stuntaneous** [comment]
I'm getting a choppy framerate with 720p desktop res, 8mbit stream, audio enabled, Atmos 0.12.0 and FW 10.0.1. And of course, running very well and easily on the host computer.

**Comment by DevL0rd** [comment]
Ok try the new version guys and use the Nvidia encoder and let me know if it is better.

**Comment by DevL0rd** [comment]
> My router reboot some days ago, I'm pretty sure this is not the issue here :/
> 
> The Switch was just booted in EmuMMC before trying the homebrew :/
> Windows just rebooted after drivers install of your software too..
> 
> Also, to me I'm 100% sure that the analog output just 8 directions :/

It definitely does not, do you have a remapper?

**Comment by campofmusic** [comment]
now i dont see any video even with CPU enabled,
the Star Streamer button i need to click couple times until it actually connect but after that i the says its not connected.
the weird thing in my switch it did connected but i can only stream sound, glitched sound but sound.

**Comment by johnlabor** [comment]
10mbps nearly no issues on my side with CPU encoding.
20mbps have some choppy tho however 10mbps is way more than what you need to have a great picture quality.

**Comment by DevL0rd** [comment]
Yeah 5 to 10 is best. any more is overkill and creates some performance issues.

**Comment by DevL0rd** [comment]
> now i dont see any video even with CPU enabled,
> in the Start Streamer button i need to click couple times until it actually connect but after that i its says its not connected.
> the weird thing in my switch it did connected but i can only stream sound, glitched sound but sound.

You sound like your getting the worst of it lol.
Add me on discord and we can work it out later when I'm up.
DevL0rd#3384

**Comment by campofmusic** [comment]
@DevL0rd 
yeah lol,
i tried to sent to DevL0rd#3384
but there's no such name,
changed the zero to O maybe you'll get it.

thank for the help man!

**Comment by DevL0rd** [comment]
oh yeah that is it XD

**Comment by oocyberkevinoo** [comment]
Well, tried, absolutely no good results :

nvidia Encoder :
- 60FPS more often, like REALLY more often
- REALLY BIG LATENCY, only audio is sync

CPU Encoding :
- Same as before, nothing changed

Also, yeah, it have Analog Control, that was the game I tried that don't use it -_-
