### ISSUE TITLE
Ps vita Port <3 

### ISSUE THREAD

**Issue by Zarke669** [DevL0rd/SkyNX#12]
is there a possibility to port to ps vita?

**Comment by DevL0rd** [comment]
Well since you asked so nicely...
Ok, well, no sadly XD I don't have a ps vita to test on and without a psvita I would never get it working haha.

**Comment by mirh** [comment]
Or you could make this adopt the moonlight's protocol. 
Not sure if it's better or worse designed. 
https://github.com/moonlight-stream/moonlight-common-c/issues/29

**Comment by DevL0rd** [comment]
It's definitely better but poses an issue for hardware decoding on switch. It would not be good lol

**Comment by mirh** [comment]
Uhm? That's the official nvidia protocol used in the shields. 
I would guess that if there is somebody knowing how to squeeze X1 it is them.
