### ISSUE TITLE
Error after click "Start Streamer"

### ISSUE THREAD

**Issue by knightofnet** [DevL0rd/SkyNX#14]
Hi,

After following the instructions for setting up SkyNx, I get the following error on the computer side:

```
CemuHook Server ID: 2108125937
Waiting for connection...
CemuHook: Listening at 0.0.0.0:26760
Connected to Switch!
D:\Logiciels\Outils\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\node_modules\struct\index.js:355   thr
ow new Error('Buffer size too small for struct layout !');   ^ Error: Buffer size too small for struct layout ! at Struct._setBuff.setBuffer (D:\Logiciels\Outils\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\node_module
s\struct\index.js:355:19)   at parseInputStruct (D:\Logiciels\Outils\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\main.js:145:9) at Socket.<anonymous> (D:\Logiciels\Outi
ls\SkyNXStreamer-win32-ia32\resources\app\NxStreamingService\main.js:288:13)   at Socket.emit (events.js:182:13) at addChunk (_stream_readable.js:283:12) a
t readableAddChunk (_stream_readable.js:264:11)   at Socket.Readable.push (_stream_readable.js:219:10) at TCP.onStreamRead [as onread] (intern
al/stream_base_commons.js:94:17)
streamerProcess process exited with code 1
```

Infos about my switch : 

- FW : 9.2.0
- CFW : SX 2.9.3
- Running SkyNx from NSP forwarder, and hbmenu

And about my computer : 

- Win 10
- CPU : Intel i5-4670K 
- RAM : 16 Go
- GPU : Geforce GTX 970

Both switch and pc are on the same network: pc to router by cable, router to switch by wifi.

Whether or not there is a solution to this problem, thank you for your work: it is an excellent idea that deserves to be supported as much as possible.

**Comment by DevL0rd** [comment]
Redownload the app, if you use the HB app store, then it may not have been updated already

**Comment by knightofnet** [comment]
Yes, it works.
The update came in on the HB app store.
Thank you!
