### ISSUE TITLE
No sound.

### ISSUE THREAD

**Issue by Kev63** [DevL0rd/SkyNX#15]
Hi.

Everything's working like a charm but the audio part. I can't make it work. I uninstalled the driver, reinsalled it, nothing. Uninstalled it again, reboot computer, reinstalled, still nothing.

Windows 10 x64 computer with Switch FW 10.0.1 SX OS.

Cheers.

**Comment by Stuntaneous** [comment]
It's been hit and miss for me in my 10 minutes of experience. On my first try the sound crackled and was not sounding healthy. The second try it was fine. And now since then, no sound. Tried firing it up after a game is launched and beforehand.

**Comment by Eolu** [comment]
I see this dialog whenever I try to install the audio driver (on my Win 10 x64 PC):

![image](https://user-images.githubusercontent.com/4412674/80314207-302ccd80-87be-11ea-9189-09db43eb519b.png)

Haven't been able to dig anything up to explain this as of yet.

**Comment by DevL0rd** [comment]
> I see this dialog whenever I try to install the audio driver (on my Win 10 x64 PC):
> 
> ![image](https://user-images.githubusercontent.com/4412674/80314207-302ccd80-87be-11ea-9189-09db43eb519b.png)
> 
> Haven't been able to dig anything up to explain this as of yet. The DLL is in the location shown in this dialog.

Join us here for this one:
https://github.com/DevL0rd/SkyNX/issues/19

**Comment by DevL0rd** [comment]
Let me update myself to the latest firmware and do some test. I'll be right back for testing

**Comment by DevL0rd** [comment]
What's everyones console log when this happens?

**Comment by DevL0rd** [comment]
ok we figured it out, try installing: VCredist
https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555

And re-install the audio driver

**Comment by DevL0rd** [comment]
Yeah this fixed it. I'm closing it up now.
