### ISSUE TITLE
Sleep\stream restart\etc. can cause switch to freeze.

### ISSUE THREAD

**Issue by xzyxzy** [DevL0rd/SkyNX#18]
FW: 9.2.0
SX OS: 2.9.4
Launching via SkyNX redirector

Examples of what can cause switch to freeze:
1) Dock while stream. 
2) Wifi drop.
3) Sleep.
Stream freezes, app freezes (doesn't respond to stream restart). Restart app -> switch freeze. 
At first it capable of showing charge and volume, yet you can't home-out. Then after few seconds switch completely freezes, screen doesn't turns off via button.

**Comment by DevL0rd** [comment]
This is already on the known issues list. Well some of them.

Sleep, and docking.

But wifi drop shouldn't be an issue. I'll look into it

**Comment by DevL0rd** [comment]
TCP stream checking was the issue. Now the data is verified to be correct before using it

**Comment by ZRupp** [comment]
Just had this happen to me too. It's really hard to push a payload to my switch after I restart after this crash for some reason.

**Comment by Peniskoker** [comment]
Really loving the app so far. Is the sleep bug fixed?

**Comment by Peniskoker** [comment]
Joehoe?

**Comment by goldsziggy** [comment]
@DevL0rd I am interesting in helping out for this issue, do you have any hunch as to what could be causing the issue?

**Comment by DevL0rd** [comment]
Finally fixed <3
