### ISSUE TITLE
Can't install audio driver

### ISSUE THREAD

**Issue by URBANsUNITED** [DevL0rd/SkyNX#19]
No matter which version I try, I always get this error by pushing the install audio driver:

![image](https://user-images.githubusercontent.com/6212300/80314231-a2b6a100-87f0-11ea-93be-75015cc62372.png)

The dll exists
![image](https://user-images.githubusercontent.com/6212300/80314285-deea0180-87f0-11ea-8213-caf6985f4fd3.png)

Using a fresh Windows 10 Pro - 1909 
AMD RX 570

Thanks
URBANsUNITED

**Comment by DevL0rd** [comment]
Thanks for posting the issue here.

Do you have a discord, so i can send a file over?
Mine is DevL0rd#3384

**Comment by URBANsUNITED** [comment]
Yeah, I have:

URBANsUNITED#1563

Will Check tomorrow morning

**Comment by richmond94** [comment]
Having the same issue, would it be possible to get the file too? Discord is: Franticrichmond #4888

**Comment by DevL0rd** [comment]
ok we figured it out, try installing: VCredist
https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555

**Comment by URBANsUNITED** [comment]
Thanks DevL0rd!
That was the fix for all issues I had incl. the audio driver problem!
You should note this in the readme!

Thank you for this fantastic piece of software! It works perfectly great!  Gears 5 and Jedi Fallen Order playing great!!!! ❤

**Comment by Eolu** [comment]
Yep, that fixed the audio driver error for me too.

**Comment by reinzanini** [comment]
I've the latest vcredist installed but it's still throwing the same error as the OP's. The link you posted is dead atm, so dunno what to do
