### ISSUE TITLE
Error on close

### ISSUE THREAD

**Issue by MPTrxx** [DevL0rd/SkyNX#2]
Hi,
Just did a really quick test on my switch and it seemed to run great at 720p. Had this pop up when I closed the streamer app. Not sure if I had hit stop streamer before closing.
Cheers for the awesome work.

![image](https://user-images.githubusercontent.com/32729816/79866046-82b56500-841f-11ea-8f02-98fb5e129ea8.png)

**Comment by DevL0rd** [comment]
@MPTrxx No you don't need too. It's my bad for improperly handling the on close.

Thanks for leaving a screenshot though! I will patch it up before next release.

**Comment by DevL0rd** [comment]
@MPTrxx Did you happen to test audio? There is a settings button with install audio driver, I havn't tested on another machine but I did it to work without screen capture recorder.

**Comment by DevL0rd** [comment]
Fixed!
