### ISSUE TITLE
Nvidia Codecs reduced some latency on video output side but increase controller response time

### ISSUE THREAD

**Issue by johnlabor** [DevL0rd/SkyNX#20]
In all my test the nvidia codecs is nice to reduce some latency putting the switch screen and my monitor side-by-side for delays, but when you actually control the character in game it takes more than half a second for the character to respond.

The weird thing is the PC end has no issue, only the switch end, and switch back to the CPU encoding works as intended which has around maybe 70-100ms lag delay and is still playable.

Thanks,
John

**Comment by DevL0rd** [comment]
You know I noticed that also. I keep coding and not actually playing any games, just quick tests. I'll get on it when I'm up tommorrow and see what's going on. I think it is because it is using CPU to rescale so it pipes it and filters it a second time.

**Comment by DevL0rd** [comment]
Also what is your Mbps at?

**Comment by johnlabor** [comment]
10mbps, I test 6 and it does not as smooth as 10.
Like you said in another post 20 is really not needed on handheld and even on big screen many 1080p streams on twitch is having 6mbps. I think with a 3-10 will give the best balanced result on 720p.

**Comment by johnlabor** [comment]
-preset            <int>        E..V.... Set the encoding preset (from 0 to 11) (default medium)
     default                      E..V.... 
     slow                         E..V.... hq 2 passes
     medium                       E..V.... hq 1 pass
     fast                         E..V.... hp 1 pass
     hp                           E..V.... 
     hq                           E..V.... 
     bd                           E..V.... 
     ll                           E..V.... low latency
     llhq                         E..V.... low latency hq
     llhp                         E..V.... low latency hp
hq = high quality (I think libnvenc uses this)
hp = high performance


Using nvenv can define a preset. I didnt see you having this on your main.js for nvidia, but you have for cpu.
When I use it for my own project, setting to default would result in medium which is hq 1 pass. Seems not ideal for the streamer here.

I recommend try out -preset ll at least, and adding -preset llhp for possible best performance and lowest latency.

Hopefully I get my comments right here.

Thanks,
John

**Comment by DevL0rd** [comment]
So I have a bit of an issue, and that is that my system is a little overkill and I'm unable to tell a big difference.
I have spent almost 5 hours tweaking to no avail :/
Tried alot fo the things you said aswell with not much benifit. But I got a little further...
Using the presets seemed to be slower for me but idk I have been up all night with this one and am so exausted. Maybe I just need to wake up with a fresh perspective.

Wanna try running ffmpeg from command line with these args and try tweaking it? 

Try these args replacing the things in <> of course with.
-probesize 50M -hwaccel auto -f gdigrab -framerate 60 -video_size <screenWidth>x<screenHeight> -offset_x 0 -offset_y 0 -draw_mouse 1 -i desktop -c:v h264_nvenc -rc cbr_ld_hq -zerolatency 1 -f h264 -vf scale=1280x720 -pix_fmt yuv420p -profile:v baseline -cq:v 19 -g 999999 -b:v 5M -minrate 2M -maxrate 5M -bufsize <(quality / (fps / 4))>M tcp://<IP>:2222

I am so bogged down on figuring this one out. Cpu encoding seems to be going way faster DX

**Comment by DevL0rd** [comment]
Here is this if it helps
https://forum.videohelp.com/threads/381841-Unterstanding-how-to-use-ffmpeg-nvenc

**Comment by johnlabor** [comment]
So maybe you can have a guide for me on how to compile the thing so I can fork and test it on my side? I also have a high performance computer and in I don’t think the issue is related to video encoding. The cpu has less load as expected when running on nvenc and eye testing really not seeing issues.

**Comment by DevL0rd** [comment]
So for the nx streamer service, and the app, it's all node.js.

If you install node.js, and simply click my Install Modules bat in both the streamer directory, and the streamer service directory, it should auto install every thing you need. Then to build the streaming service, click build, and then you can test the changes with the main streamer UI without compiling by hitting the run.bat.

You can test the streamer service with it's run.bat, but I have not updated it with latest params.
But you need to compile the streamer service for it to be used in the streamer ui.

**Comment by DevL0rd** [comment]
I have been really slapping this together fast.. soo... don't mind the completely unmanaged code haha

**Comment by DevL0rd** [comment]
@johnlabor if you get this working right btw. I don't mind sending you some of my donations I got so far :) I'll try again later aswell

**Comment by johnlabor** [comment]
I have tried a lot of combinations and here is what I think it happens:
1. Use "-preset llhp" without using "-rc" since the latter will override the preset, and it is more delay overall.

2. Use "-2pass 0", "-delay 0" might also reduce some latency.

3. "-cq 1" only works in vbr hence what we were doing in (1).

4. Run my game in windowed mode, use another window to half-cover the game window, no delays. As soon as I allow the entire game exposed to the screen, delays will always ramp up as it seems GPU needs to render more things in the game on screen thus put the ffmpeg process priority on the side. Putting ffmpeg on high priority does not help.
https://forums.developer.nvidia.com/t/how-to-give-gpu-priority-to-my-process/43205/4
This post seems suggest a similar behavior.

5. Every 6-7 seconds, switch screen will show the game suddenly speed very fast for 1 second as if it is now knows it is lagging behind and trying to jump to the current frame that is supposed to output.

6. The CPU encoding obvious does not interfering with the GPU when rendering heavy-load GPU bound games, and does not has the above behavior.

7. I am not sure if a alternative solution to ffmpeg such as Ultragrid would work.
https://github.com/CESNET/UltraGrid
Will still check if I can change the priority settings of the GPU.

In the meantime, CPU is still working well and I dont think I can tune it better than the current state as some lag will exist as we are streaming.

I think now we can label the GPU option as experimental.

Thanks,
John

**Comment by DevL0rd** [comment]
Will do. I wil ltry these changes tommorrow :)

Thanks for looking into it :)

**Comment by PolCPP** [comment]
Hrm have you tried using quicksync (h264_qsv) instead of the nvidia encoder? Quality is worse but i was trying (more like trying to since, skynx seems to run awfully slow on my switch) but i feel like it also seems to come with the same latency issues compared to cpu encoding.

**Comment by DevL0rd** [comment]
Yeah I have no idea why the hardware accelerated encoders are perforning so bad :/
