### ISSUE TITLE
Some full-screen games freeze video streaming 

### ISSUE THREAD

**Issue by knightofnet** [DevL0rd/SkyNX#21]
FW: 9.2.0
SX OS: 2.9.4
Launching via SkyNX redirector
SkyNx  v1.2

In some games/applications that switch to full screen the video transmission is no longer transmitted (and the last frame before full screen remains displayed).

Example: Citra

Windowed, the transmission is clear. But if I press F11 to switch to fullscreen, the image freezes on the switch. The sound and controls still work.
When I exit fullscreen, video transmission resumes.

**Comment by johnlabor** [comment]
I manage to resolve that by running games natively or third party tool in borderless windowed mode. Seems something related to exclusive control of monitors by games and some work some doesn’t in full screen mode

**Comment by xzyxzy** [comment]
Can confirm. Testing with FFXIV, pre-Nvidia encoding was streaming fullscreen just fine, but current version is not working (I hear device connect sound in windows (pad) but no video starts on NSW (no changes from bubble display at all)) in either of streaming modes.

**Comment by DevL0rd** [comment]
Windwos prioritizes fullscreen applications, sometimes to the detriment of background processes, i'm sure there is a workaround in code somewhere, but for now run in windowed borderless. Things run smoother in that mode anyway
