### ISSUE TITLE
No controls after updating to latest build

### ISSUE THREAD

**Issue by richmond94** [DevL0rd/SkyNX#24]
Updated to latest build today but controls now seem to not work, windows picks up that there is a controller and I can calibrate the sticks but when it comes to games nothing works. I've also reinstalled the drivers

**Comment by DevL0rd** [comment]
There are no change to the input methods in this version, reboot windows, and make sure there isn't any controllers takign slot 1

**Comment by richmond94** [comment]
It was a screw up on my side! The bindings for ff7 was messed up. Sorry!

**Comment by DevL0rd** [comment]
nah it's good man. glad to hear it is working :)
