### ISSUE TITLE
Controllers not working 

### ISSUE THREAD

**Issue by luansergiomattos** [DevL0rd/SkyNX#27]
I tried restarting windows many times and even reinstall the drives in settings. I have never used In-Home-Switching.

My OS is windows 10 ltsc and I'm running Atmosphère 0.12.0 on my switch

Any solution I can try?

**Comment by DevL0rd** [comment]
Can you start the streamer again, connect, disconnect, copy the console log and paste it here for me?

**Comment by AidanDaniel97** [comment]
Same issue here, reinstalled drivers and it was working on an older version, I only updated my streamer.

`CemuHook Server ID: 3790486239
Waiting for connection...
CemuHook: Listening at 0.0.0.0:26760
Connected to Switch!
Using CPU Encoding
ffmpeg version git-2020-04-22-2e38c63 Copyright (c) 2000-2020 the FFmpeg developers  built with gcc 9.3.1 (GCC) 20200328 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf libavutil 56. 42.102 / 56. 42.102 libavcodec 58. 80.100 / 58. 80.100 libavformat 58. 42.101 / 58. 42.101 libavdevice 58. 9.103 / 58. 9.103 libavfilter 7. 79.100 / 7. 79.100 libswscale 5. 6.101 / 5. 6.101 libswresample 3. 6.100 / 3. 6.100 libpostproc 55. 6.100 / 55. 6.100
ffmpeg version git-2020-04-22-2e38c63 Copyright (c) 2000-2020 the FFmpeg developers  built with gcc 9.3.1 (GCC) 20200328 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf libavutil 56. 42.102 / 56. 42.102 libavcodec 58. 80.100 / 58. 80.100 libavformat 58. 42.101 / 58. 42.101 libavdevice 58. 9.103 / 58. 9.103 libavfilter 7. 79.100 / 7. 79.100 libswscale 5. 6.101 / 5. 6.101 libswresample 3. 6.100 / 3. 6.100 libpostproc 55. 6.100 / 55. 6.100
[gdigrab @ 0522df40] Capturing whole desktop as 1280x720x32 at (0,0)
[dshow @ 067dd580] Could not find audio only device with name [virtual-audio-capturer] among source devices of type audio. [dshow @ 067dd580] Searching for audio device within video devices for virtual-audio-capturer
[dshow @ 067dd580] Could not enumerate audio only devices (or none found).
audio=virtual-audio-capturer: I/O error
AudioProcess process exited with code 1
Input #0, gdigrab, from 'desktop':  Duration: N/A, start: 1588343088.940282, bitrate: 1769497 kb/s Stream #0:0: Video: bmp, bgra, 1280x720, 1769497 kb/s, 60 fps, 60 tbr, 1000k tbn, 1000k tbc
Stream mapping:  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264)) Press [q] to stop, [?] for help
[libx264 @ 06c82f40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 06c82f40] profile Constrained Baseline, level 3.2, 4:2:0, 8-bit Output #0, h264, to 'tcp://192.168.1.127:2222':  Metadata: encoder : Lavf58.42.101 Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 5000 kb/s, 60 fps, 60 tbn, 60 tbc Metadata: encoder : Lavc58.80.100 libx264 Side data: cpb: bitrate max/min/avg: 5000000/0/5000000 buffer size: 2500000 vbv_delay: N/A
frame=  46 fps=0.0 q=0.0 size= 437kB time=00:00:00.76 bitrate=4673.9kbits/s dup=7 drop=0 speed=1.52x
frame=  76 fps= 75 q=0.0 size= 743kB time=00:00:01.26 bitrate=4802.6kbits/s dup=7 drop=0 speed=1.26x
streamerProcess process exited with code null`

**Comment by AidanDaniel97** [comment]
I figured out that my .nro file was out of date, so I updated this to the latest and it is working now. Perhaps the same issue you have @luansergiomattos

**Comment by luansergiomattos** [comment]
> I figured out that my .nro file was out of date, so I updated this to the latest and it is working now. Perhaps the same issue you have @luansergiomattos

You're right, I updated the nro file and now everything is working as intended
Thanks for the help @AidanDaniel97 @DevL0rd
