### ISSUE TITLE
Stream is too dark (low gamma?)

### ISSUE THREAD

**Issue by acrobat09** [DevL0rd/SkyNX#28]
When playing games with dark scenes, it's almost impossible to see anything on the switch screen, despite it being visible on the computer monitor.

Please provide an option to adjust the gamma of the stream.

**Comment by DevL0rd** [comment]
Good idea to add the gamma adjustment. It will add latency, but some computer monitors are not that great so I can see a low darkness setting on them would work and not translate well to the switches panel.

I have not ran into this myself, but I did have another user with the same issue. His monitor was high gamma, so he could se everything on his monitor fine, but not on the switch where the contrast was better. So a slider would fix this definitely.

**Comment by acrobat09** [comment]
For now I am working around the issue using ReShade, but a slider in SkyNX would be perfect, thanks!
