### ISSUE TITLE
Massive audio quality drop in Docked mode.

### ISSUE THREAD

**Issue by swagathaur** [DevL0rd/SkyNX#30]
Tested using a variety of Quality amounts, using both CPU and Nvidia encoding, and with video both enabled and disabled. When in docked mode, audio becomes barely comprehensible distorted noise.

**Comment by OldGnashburg** [comment]
Can confirm I'm having this issue too. Handheld is infinitely better, but not perfect.

**Comment by Anti-Apple4life** [comment]
same

**Comment by StrangeOne101** [comment]
Also having this issue. Following to see where this leads.

Note: The forwarder failed to install, but without it everything seems to work fine from what I've seen. Not sure if that's related

**Comment by konrad-ch** [comment]
I confirm, sound on docked mode is horrible. It's quite a shame because beside of that the software is awesome and works great. But for me, its unusable with that sound... :<
