### ISSUE TITLE
AMD gpu displayports stop working after restart

### ISSUE THREAD

**Issue by kirigar** [DevL0rd/SkyNX#32]
I tried installing the software and when it prompted me to restart I restarted. However after restarting, the monitor plugged into my displayport port suddenly stopped working. I have tried different monitors but it does seem like my GPU is at fault here.

I also tried booting into my linux installation and that seemed to work, however the resolution of my displayport monitors automatically gets set to 640x480.

I'm not a 100% sure that this program caused it, but I'm not sure what else could have caused it.
I've also tried uninstalling the controller and audio drivers but that didn't seem to change anything.

I do have a HDMI port on my gpu which still works fine.

**Comment by DevL0rd** [comment]
It seems to be coincidence. there is nothing about the software's code that could ever cause issues like this.
