### ISSUE TITLE
Stream Closing instantly even with controller drivers installed 

### ISSUE THREAD

**Issue by NoctisDeLucis** [DevL0rd/SkyNX#34]
Hello, 
I've been trying to make the streaming work correctly with no avail.
If i launch the stream and don't touch at my joycons it works but i wished i could use them as i don't have any wireless controller

**Comment by DevL0rd** [comment]
post your log here. Also use the latest version I released today

**Comment by DevL0rd** [comment]
Also make sure your app is updated

**Comment by NoctisDeLucis** [comment]
I'll give it a try, if it still doesn't work i will post the logs

**Comment by NoctisDeLucis** [comment]
Hello, its me again, so i tried the new version everything seems to work great now, but i have no sound

**Comment by NoctisDeLucis** [comment]
CemuHook Server ID: 3464577254
Waiting for connection...
CemuHook: Listening at 0.0.0.0:26760
Connected to Switch!
Using CPU Encoding
Plugged in controller 1.
ffmpeg version git-2020-04-22-2e38c63 Copyright (c) 2000-2020 the FFmpeg developers  built with gcc 9.3.1 (GCC) 20200328 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf libavutil 56. 42.102 / 56. 42.102 libavcodec 58. 80.100 / 58. 80.100 libavformat 58. 42.101 / 58. 42.101 libavdevice 58. 9.103 / 58. 9.103 libavfilter 7. 79.100 / 7. 79.100 libswscale 5. 6.101 / 5. 6.101 libswresample 3. 6.100 / 3. 6.100 libpostproc 55. 6.100 / 55. 6.100 ffmpeg version git-2020-04-22-2e38c63 Copyright (c) 2000-2020 the FFmpeg developers built with gcc 9.3.1 (GCC) 20200328 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf libavutil 56. 42.102 / 56. 42.102 libavcodec 58. 80.100 / 58. 80.100 libavformat 58. 42.101 / 58. 42.101 libavdevice 58. 9.103 / 58. 9.103 libavfilter 7. 79.100 / 7. 79.100 libswscale 5. 6.101 / 5. 6.101 libswresample 3. 6.100 / 3. 6.100 libpostproc 55. 6.100 / 55. 6.100
[gdigrab @ 0684d080] Capturing whole desktop as 1280x720x32 at (0,0)
Input #0, gdigrab, from 'desktop':  Duration: N/A, start: 1589288044.799463, bitrate: 1769497 kb/s Stream #0:0: Video: bmp, bgra, 1280x720, 1769497 kb/s, 60 fps, 60 tbr, 1000k tbn, 1000k tbc
Stream mapping:  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264)) Press [q] to stop, [?] for help
[libx264 @ 0685f900] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0685f900] profile Constrained Baseline, level 3.2, 4:2:0, 8-bit Output #0, h264, to 'tcp://192.168.0.21:2222':  Metadata: encoder : Lavf58.42.101 Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 5000 kb/s, 60 fps, 60 tbn, 60 tbc Metadata: encoder : Lavc58.80.100 libx264 Side data: cpb: bitrate max/min/avg: 5000000/0/5000000 buffer size: 2500000 vbv_delay: N/A
switchFps=62
frame=  46 fps=0.0 q=6.0 size= 437kB time=00:00:00.76 bitrate=4673.9kbits/s dup=9 drop=0 speed=1.51x
switchFps=0
switchFps=0
[dshow @ 0499a480] Could not run graph (sometimes caused by a device already in use by other application) audio=virtual-audio-capturer: I/O error
IAudioCaptureClient::setup failed
frame=  77 fps= 75 q=1.0 size= 769kB time=00:00:01.28 bitrate=4911.1kbits/s dup=14 drop=0 speed=1.26x
AudioProcess process exited with code 1
switchFps=67
frame= 107 fps= 70 q=24.0 size= 1267kB time=00:00:01.78 bitrate=5820.9kbits/s dup=14 drop=0 speed=1.16x
switchFps=67
frame= 138 fps= 68 q=14.0 size= 1476kB time=00:00:02.30 bitrate=5255.5kbits/s dup=17 drop=0 speed=1.13x
switchFps=60
frame= 168 fps= 66 q=31.0 size= 1907kB time=00:00:02.80 bitrate=5579.1kbits/s dup=17 drop=0 speed= 1.1x
switchFps=60
frame= 199 fps= 65 q=18.0 size= 2152kB time=00:00:03.31 bitrate=5315.5kbits/s dup=17 drop=0 speed=1.09x
switchFps=59
frame= 229 fps= 64 q=22.0 size= 2322kB time=00:00:03.81 bitrate=4983.8kbits/s dup=17 drop=0 speed=1.07x
switchFps=59
frame= 259 fps= 64 q=13.0 size= 2728kB time=00:00:04.31 bitrate=5177.3kbits/s dup=20 drop=0 speed=1.06x
switchFps=58
frame= 290 fps= 63 q=11.0 size= 2926kB time=00:00:04.83 bitrate=4959.2kbits/s dup=20 drop=0 speed=1.06x
switchFps=58
frame= 320 fps= 63 q=7.0 size= 3225kB time=00:00:05.33 bitrate=4953.1kbits/s dup=20 drop=0 speed=1.05x
switchFps=62
frame= 351 fps= 63 q=4.0 size= 3547kB time=00:00:05.85 bitrate=4966.4kbits/s dup=20 drop=0 speed=1.05x
switchFps=62
frame= 381 fps= 63 q=22.0 size= 4041kB time=00:00:06.35 bitrate=5212.8kbits/s dup=20 drop=0 speed=1.04x
switchFps=59
frame= 412 fps= 62 q=34.0 size= 4417kB time=00:00:06.86 bitrate=5269.7kbits/s dup=22 drop=0 speed=1.04x
switchFps=59
frame= 444 fps= 62 q=16.0 size= 4520kB time=00:00:07.40 bitrate=5003.7kbits/s dup=23 drop=0 speed=1.04x
switchFps=59
frame= 474 fps= 62 q=0.0 size= 4791kB time=00:00:07.90 bitrate=4968.4kbits/s dup=23 drop=0 speed=1.03x
switchFps=59
frame= 506 fps= 62 q=14.0 size= 5276kB time=00:00:08.43 bitrate=5125.3kbits/s dup=27 drop=0 speed=1.03x
switchFps=60
switchFps=60
frame= 538 fps= 62 q=13.0 size= 5467kB time=00:00:08.96 bitrate=4994.7kbits/s dup=29 drop=0 speed=1.03x
switchFps=60
frame= 568 fps= 62 q=11.0 size= 5750kB time=00:00:09.46 bitrate=4975.7kbits/s dup=29 drop=0 speed=1.03x
streamerProcess process exited with code null

**Comment by DevL0rd** [comment]
Are you using anything else that captures audio? Maybe a virtual sounds device?

**Comment by NoctisDeLucis** [comment]
I do but they are disabled, do i need to unistall it ?

**Comment by DevL0rd** [comment]
I doubt it but I would try disabling the software in some way. Seems like the audio capture device is in use by something else.
Sorry for my slow response, I'v been pretty busy with the work
