### ISSUE TITLE
[Feature Rquest] USB Mode 

### ISSUE THREAD

**Issue by SakuraLeif** [DevL0rd/SkyNX#36]
Here from GBATemp!

We could use USB connectivity for offline functionality (or just a bad connection).

**Comment by DevL0rd** [comment]
Thanks for the post! This will help me keep track of it for next update

**Comment by Visualwit** [comment]
I NEED IT MY SWITCH IS NOT DOING WELL WITH SKYNX!!!

**Comment by coffandro** [comment]
So did this get implemented?
I play on semi public wifi where you can't actually connect to other devices on the network.

**Comment by NumanTF2** [comment]
still not implemented?
