### ISSUE TITLE
Request: addition of a client-side option that remotely activates the server.

### ISSUE THREAD

**Issue by baneonplane** [DevL0rd/SkyNX#38]
It seems like having SkyNX server running without a client attached still sucks up wifi. One possibility to fix that is to have a button or something in the SkyNX client that remotely activates the server. That would be a huge help. Should also be fairly easy to implement - just have a service running on some port on the server, and launch the server when it receives a signal from the Switch. The problem would be security - I don't want anyone with a Switch being able to access my computer. Having some sort of user-customizable username and passphrase (that can only be changed from the server) would likely fix that.

Edit: alternatively, having a random token on each install of SkyNX that you have to enter on the server would work, as long as the token never changes.

**Comment by baneonplane** [comment]
I'd be happy to code this. I'm trying to build the program, but I keep getting this error. Do you know what could be causing that? Does it build properly on your computer?

```
/mnt/d/code/skynx/SkyNX/SkyNX/source/main.c: In function 'switchInit':
/mnt/d/code/skynx/SkyNX/SkyNX/source/main.c:80:5: error: too few arguments to function 'plInitialize'
   80 |     plInitialize();
      |     ^~~~~~~~~~~~
In file included from /opt/devkitpro/libnx/include/switch.h:82,
                 from /mnt/d/code/skynx/SkyNX/SkyNX/source/main.c:37:
/opt/devkitpro/libnx/include/switch/services/pl.h:36:8: note: declared here
   36 | Result plInitialize(PlServiceType service_type);
```

**Comment by DevL0rd** [comment]
update your libnx?

**Comment by DevL0rd** [comment]
and the server is always waiting for a connection, so when the app starts it should auto connect.
Why have a server waiting to start the server?

**Comment by DevL0rd** [comment]
You could also on initial connection, generate a token and after that the server could lock into that token and never accept others.
Though I'm planning in the future to allow multiple switches to connect at the same time. Could be cool for couch co-op games.

**Comment by baneonplane** [comment]
Never mind. Sorry, it seemed that the server uses bandwidth even when not connected to the Switch. But I checked and that doesn't seem to be an issue. That said, some sort of function where a passtoken is needed for a Switch to connect would be great. For instance, just showing a (static) random integer to use as a token on the client side and asking the user to input any valid tokens that they want to use on the server side.
