### ISSUE TITLE
Creation of Settings file causes setting to fail in application after first open

### ISSUE THREAD

**Issue by xlim3y** [DevL0rd/SkyNX#39]
Whenever i launch the application once after unzipping it, the settings file creates, and i can open the settings tab and select various values, but then whenever I open it again, the settings tab on the app doesn't open. it just stays on the visual of whatever other tab i had open first. It also will not auto launch the program, or start the stream, despite settings those values to True.

**Comment by MrSnoozles** [comment]
Exactly the same here. Did you by any chance install the streamer and then move it to another location?

**Comment by DevL0rd** [comment]
whoopsie...  prolly my bad. lemme poke around really quick

**Comment by DevL0rd** [comment]
weird I am not having this issue.. But a few people are. This is the latest version right?
Can you paste your config here after making the issue happen again?
And one more thing, can you set debug to true in the config file, and use the new icon on the titlebar, next to minimze, to open the debug console.
And then let me know if there are any red errors in there. If the issue is happening, and there are no red errors in the console. Try hitting the refresh button next to the debug console button on the title bar

**Comment by xlim3y** [comment]
Ok, so the setting that causes this issue is the "Start Streamer Automatically"

I can change every other setting with no problem, but once I turn that on, closing the app and reopening it does not allow the settings screen to function.

This time, when i closed out the app after turning that setting on, I got the attached Java error.  Also attaching the settings.json as requested after causing the issue.  I did not see any red text in the debugger.

Using the refresh button on after launching new did not correct the error, the settings screen still will not open.

**Comment by xlim3y** [comment]
[settingstxt.txt](https://github.com/DevL0rd/SkyNX/files/4634913/settingstxt.txt)

![Error](https://user-images.githubusercontent.com/64167108/82060928-de6cba00-967c-11ea-9f55-7a86f524943a.PNG)

**Comment by DevL0rd** [comment]
alright that may be what I needed to find the issue.

**Comment by DevL0rd** [comment]
ohh yeah I load the settings module before the streamer control module.
So when settings trys to auto start, it can't use the connect function yet because it doesn't exist yet hehe.
Now I feel dumb, but I appreciate your help in finding this bug.

**Comment by DevL0rd** [comment]
I will have to push an update tommorrow along with a few other fixes as I have work today.
But at least I know what happened lol

**Comment by MrSnoozles** [comment]
![2020-05-15 22 55 55](https://user-images.githubuserlaontent.com/17496592/82095436-4d8af280-96ff-11ea-94ea-a904a4746b73.jpg)
Probably too late, but maybe 8t helps to confirm the fix ;)

**Comment by MrSnoozles** [comment]
Probably too late, but maybe it helps to confirm the fix ;)

![2020-05-15 22 59 10](https://user-images.githubusercontent.com/17496592/82095687-d73ac000-96ff-11ea-8a5b-e4a5959464a6.jpg)

**Comment by DevL0rd** [comment]
yep just what i thought haha
Thanks for confirming for me. I only looked through the code, couldn't test it while working

**Comment by DevL0rd** [comment]
Using a projector eyyy?

**Comment by MrSnoozles** [comment]
@DevL0rd Any news on an update? This is an amazing piece of software you made, but it still has a couple hiccups. Would be great to see it get the polishing it deserves :)
