### ISSUE TITLE
AMD encoding doesn't work

### ISSUE THREAD

**Issue by sacreduniverse** [DevL0rd/SkyNX#40]
Rocking nvidia works great but if I load it on AMD it launches fine but my switch never connects to it.

**Comment by DevL0rd** [comment]
Do you have a amd gpu? Because I doubt you have both haha but I could be surprised :)

**Comment by sacreduniverse** [comment]
I didn’t even think about that, well you should note that on the app or something so you don’t get people who are super excited and don’t read everything like me.
