### ISSUE TITLE
Request: pass token to use as validation.

### ISSUE THREAD

**Issue by baneonplane** [DevL0rd/SkyNX#41]
(I'm making a separate issue out of this so that issues can be tracked better.)
It'd be great if there was a client-server authentication mechanism. For instance - on first boot of the .nsp, you could set a random integer as a token. libnx has a function that gets a random 64-bit integer, I think. Then, before the client can connect, the token must be added to a list of valid tokens that the server has. That would make it easy to add new Switches too if/when multiplayer is implemented - just ask the server owner to add the token before you connect.

**Comment by DevL0rd** [comment]
Someone else wanted this aswell. I will do it, but sadly not much time with work and all. I'll try to get it fone for yah though :)

**Comment by baneonplane** [comment]
Thank you! I look forward to testing it! (I'm definitely not knowledgeable enough to build the code for running myself.)
