### ISSUE TITLE
Controller doesnt work

### ISSUE THREAD

**Issue by Kirf** [DevL0rd/SkyNX#44]
been trying for couple of days reinstall driver and using latest ver for nro 1.3. Everything working fine and i can see an xbox controller shown in 'device and printers'.
running on windows 7 64 pro / sx os 2.9.5 beta

CemuHook Server ID: 2197807854
Waiting for connection...
CemuHook: Listening at 0.0.0.0:26760
Connected to Switch!
Using CPU Encoding
Plugged in controller 1.
ffmpeg version git-2020-04-22-2e38c63 Copyright (c) 2000-2020 the FFmpeg developers  built with gcc 9.3.1 (GCC) 20200328 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf libavutil 56. 42.102 / 56. 42.102 libavcodec 58. 80.100 / 58. 80.100 libavformat 58. 42.101 / 58. 42.101 libavdevice 58. 9.103 / 58. 9.103 libavfilter 7. 79.100 / 7. 79.100 libswscale 5. 6.101 / 5. 6.101 libswresample 3. 6.100 / 3. 6.100 libpostproc 55. 6.100 / 55. 6.100
[gdigrab @ 00f15600] Capturing whole desktop as 1280x720x32 at (0,0)
ffmpeg version git-2020-04-22-2e38c63 Copyright (c) 2000-2020 the FFmpeg developers  built with gcc 9.3.1 (GCC) 20200328 configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
 libavutil 56. 42.102 / 56. 42.102 libavcodec 58. 80.100 / 58. 80.100 libavformat 58. 42.101 / 58. 42.101 libavdevice 58. 9.103 / 58. 9.103 libavfilter 7. 79.100 / 7. 79.100 libswscale 5. 6.101 / 5. 6.101 libswresample 3. 6.100 / 3. 6.100 libpostproc 55. 6.100 / 55. 6.100
Incorrect data length: 417 - f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000b0bc3e00a0583e00d84ebf000000000000000000000000010000003b000000
Guessed Channel Layout for Input Stream #0.0 : stereo Input #0, dshow, from 'audio=virtual-audio-capturer':  Duration: N/A, start: 1018.909000, bitrate: 1536 kb/s Stream #0:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
Stream mapping:  Stream #0:0 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native)) Press [q] to stop, [?] for help
Output #0, s16le, to 'udp://192.168.0.16:2224?pkt_size=640':  Metadata: encoder : Lavf58.42.101 Stream #0:0: Audio: pcm_s16le, 16000 Hz, stereo, s16, 512 kb/s Metadata: encoder : Lavc58.80.100 pcm_s16le
Input #0, gdigrab, from 'desktop':  Duration: N/A, start: 1589922341.824634, bitrate: 1769497 kb/s
  Stream #0:0: Video: bmp, bgra, 1280x720, 1769497 kb/s, 60 fps, 60 tbr, 1000k tbn, 1000k tbc
Stream mapping:  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264)) Press [q] to stop, [?] for help
[libx264 @ 00f1d700] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 00f1d700] profile Constrained Baseline, level 3.2, 4:2:0, 8-bit
Output #0, h264, to 'tcp://192.168.0.16:2222':  Metadata: encoder : Lavf58.42.101 Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 20000 kb/s, 60 fps, 60 tbn, 60 tbc Metadata: encoder : Lavc58.80.100 libx264 Side data: cpb: bitrate max/min/avg: 20000000/0/20000000 buffer size: 10000000 vbv_delay: N/A
Incorrect data length: 417 - f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d0bf3e00205e3e00984ebf000000000000000000000000010000003b000000
Incorrect data length: 417 - f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070bf3e00205d3e00484ebf000000000000000000000000010000003b000000
Incorrect data length: 417 - f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010be3e00e0583e00984ebf0000000000000000000000000100000002000000
size=  32kB time=00:00:00.50 bitrate= 512.0kbits/s speed=1.01x
frame=  46 fps=0.0 q=0.0 size= 1750kB time=00:00:00.76 bitrate=18695.6kbits/s dup=10 drop=0 speed=1.52x
streamerProcess process exited with code null

#44 this number hunting me literally in everything..

**Comment by DevL0rd** [comment]
Sorry bout that, need to fix my socket buffer. Only happens for some people but been busy with work, so it's been hard to clear al the bug reports XD

**Comment by JrRadiant** [comment]
Same problem here, please fix.
