### ISSUE TITLE
Audio device selection logic is flawed

### ISSUE THREAD

**Issue by ZRupp** [DevL0rd/SkyNX#45]
SkyNX doesn't select the default audio device. I haven't looked at the code, so I can't comment on where the problem is, but in my case it always uses my audio interface that I only use for recording rather than my onboard sound, so I have to change the default device to the audio interface every time I launch SkyNX.

**Comment by DevL0rd** [comment]
What do you use for recording? This uses virtual-audio-device to record sound which defaults to capturing your default audio output device

**Comment by ZRupp** [comment]
I've just seen that it uses virtual-audio-device, so I'm not sure what's going on. I use a PreSonus AudioBox to record. I've even tried unplugging the interface, which just results in no sound output at all. This interface has given me a lot of trouble, so I wonder if it's just on my end.

**Comment by ZRupp** [comment]
I've tried this out on two laptops with a different audio interface and could not reproduce the error, so I think the error is not with SkyNX.
