### ISSUE TITLE
FPS drops when desktop resolution is 1280x720

### ISSUE THREAD

**Issue by NotMinh** [DevL0rd/SkyNX#46]
I was using the Nvidia encoder to test this out ~~but I believe the CPU encoder gave similar results~~. For reference I was streaming at 8Mbps, and at native 1080p resolution FPS is a stable 60 fps. If I switch to 720p FPS either drops to mid 30s or to single digits. Audio/video is delayed and choppy at this resolution as well. Swap A-B X-Y is the only toggle I have on.

EDIT: I tested using the CPU encoder again at 720p and it seemed to work relatively well when I'm just streaming the desktop or watching a video. Some minor FPS drops or audio stuttering while watching Youtube, but any attempt at playing a game (Portal 2) resulted in FPS jumping between 20-60. I'm not sure if this is the same issue already mentioned about the added latency with the nvidia encoder.

**Comment by NotMinh** [comment]
#5 @valmcc Did you ever figure out a solution to this bug?

**Comment by valmcc** [comment]
The only way I got around it was modifying the ffmpeg command line
arguments to stream the top left corner of my screen (1280x720) and leave
my desktop resolution as 1920x1080.

Then I would just move my game window into the corner.

No problems maintaining 60fps, but it did screw up the touchscreen mouse.
