### ISSUE TITLE
Auto stream settings is buggy.

### ISSUE THREAD

**Issue by AsixJin** [DevL0rd/SkyNX#47]
Whenever I change the setting to start the streamer automatically when it is open, close SkyNX, and open it again I can't seem to get into back into the settings not can I start the streaming. I am using Windows 10 and I can provide whatever info you need.

Note: If I change the setting by hand via notepad back to false it works as normal.

**Comment by MrSnoozles** [comment]
Should be the same as #39

**Comment by AsixJin** [comment]
Yup it's the same as the issues you mentioned. My apologizes for creating a duplicate issue.
