### ISSUE TITLE
Some apps freeze stream when set to fullscreen

### ISSUE THREAD

**Issue by Dusterrr** [DevL0rd/SkyNX#48]
I set an emulator to full screen, and when I do so, the image freezes on the switch itself. It still runs full speed on my computer, and sound still plays through the switch in real time.

**Comment by ZRupp** [comment]
I know this isn't the best solution, but a workaround is to run in borderless windowed mode if the game has it. If not, use [Windowed Borderless Gaming](https://westechsolutions.net/sites/WindowedBorderlessGaming/) until the issue has been fixed.

**Comment by Dusterrr** [comment]
That's the strange part, I did try that and it had the same effect as if I set it to fullscreen. Could just be some weird incompatibility with rpcs3.
