### ISSUE TITLE
Option to use switch as second screen

### ISSUE THREAD

**Issue by Ofdas-23** [DevL0rd/SkyNX#49]
Hello,
would it be possible to add a feature to use the switch as a second monitor using this program? It would be really cool tho!
Thanks in advance!

**Comment by DevL0rd** [comment]
That would be crazy haha The way it is done requires a screen though to record, can't make it's own screen.
But it is a fun idea :)

**Comment by y4my4my4m** [comment]
I found this project because I was looking for this solution actually.

I'm now looking into finding a way to virtualize a 2nd monitor and stream *that* to the switch.

**Comment by MrSnoozles** [comment]
Maybe a headless HDMI dongle would do the trick for you
https://eshop.macsales.com/item/NewerTech/ADP4KHEAD/
