### ISSUE TITLE
Hori Split Pad Pro doesn't work.

### ISSUE THREAD

**Issue by Fwank49** [DevL0rd/SkyNX#55]
My Hori Split Pad Pro controller doesn't work in SkyNX. None of the buttons are recognised, and it doesn't work as a mouse either. It works perfectly in every other game, and the home/screenshot buttons work in SkyNX, but nothing else works, as if they're not even plugged in.

**Comment by Monksman45** [comment]
It's working fine for me, have you tried installing the controller driver?
