### ISSUE TITLE
FPS really low and huge input lag

### ISSUE THREAD

**Issue by imsl0wer** [DevL0rd/SkyNX#58]
I'm on Latest switch fw and latest atmossphere. My FPS is like between 20-40. I use AMD Encoding and Resolution is set to 1280x720. One thing I haven't tried yet is getting closer to my router cause my wifi is really bad in my room. I will report if that fixes some stuff. But yea if I disable the Audiostream I get FPS that are closer to 60 and also using the old In-Home Switching release I got smooth 60 FPS but the Input and Audio didn't work. It's kinda weird. I'm not sure why In-Home Switching works better than SkyNX do you have an idea why?

**Comment by FlamanteGit** [comment]
did you achive fixing this?
