### ISSUE TITLE
DSUClient/Gyro+Acceleration wrong

### ISSUE THREAD

**Issue by Danos0100** [DevL0rd/SkyNX#68]
The motion data for CEMU that is transmitted over DSU at 127.0.0.1:26760 seems to be off.
If I compare it to BetterJoyForCemu connected to a Switch Pro Controller (via PC's Bluetooth), these are the acceleration axis that should be transmitted and that are transmitted:

Should be... | but at the moment it is... | position
------|---|---
-X|-X|Switch standing on the left Joy-Con
+X|+X|Switch standing on the right Joy-Con
-Y|-Z|Put Switch on its bottom (like laying normal on the table)
+Y|+Z|Upside down (screen towards the table)
+Z|-Y|Switch standing with the game cart slot upwards
-Z|+Y|Switch standing with the game cart slot towards the table

Furthermore (**and even more crucial**), the Gyro seems to be wrong as well. Besides the fact that the device orientation itself seems to be wrong, Yaw and Roll are wrong as well:
Should be...|but at the moment it is...
---|---
Pitch+|Pitch+
Pitch-|Pitch-
Yaw-|Roll+
Yaw+|Roll-
Roll+|Yaw-
Roll-|Yaw+

If the axis are correct or not can be checked pretty easy using PadTest (which is provided at https://cemuhook.sshnuke.net/padudpserver.html for example). If you connect a Pro Controller via Bluetooth and BetterJoyForCemu, you will see the 3D model's motion resemble those of the actual controller very well in PadTest/DSU Contoller Test Application. This is not the case for SkyNX atm.

This breaks compatibility with a lot of games that rely on the gyro sensor, especially titles that use it more heavily such as Nintendo Land.

**Comment by DevL0rd** [comment]
@Danos0100 will b e fixing soon. Did massive update to fix alot of issues andupdate to latest atmosphere and some other shtuff

**Comment by DevL0rd** [comment]
@Danos0100 fixed!
