### ISSUE TITLE
Problem with various Bluetooth controllers

### ISSUE THREAD

**Issue by skydark719** [DevL0rd/SkyNX#7]
I have an issue with this app.

In terms of performance, it's so nice, and the latency is minimal (although in my case, it only works at 30fps, surely in a near future you update this to better performance).

The problem is in the conflict between my Wii U Pro Controller connected via Bluetooth to my PC and the Switch connected via Bluetooth though this program.

When I succesfully connected the Switch via streaming and I close the program, my Wii U Pro Controller never works again, only works if I install Scp Driver from WiinuSoft (program to work Wii U pads on Bluetooth for PC) and install it again after restarting the PC.

If I do that, SkyNX no longer works, it stays freeze on Start-Stop Streamer until I reinstall the Bluetooth driver that this app have. But that makes no works other Bluetooth controllers.

For the rest, I have no other complaints, it's only this conflict between two Bluetooth controllers the issue.

**Comment by DevL0rd** [comment]
Ok there shouldn't be any issues with that. But just in case I automated the driver installs. 

Also what do you mean by "the Switch connected via Bluetooth though this program."? This program does not require any thing to be conencted via bluetooth, so if your joycons are connected via bluetooth, definitely unpair them.

Try these steps before installing the latest release.
remove the Scp Driver, and remove my audio and controlelr driver in the settings panel of my streamer app.

Then completely delete the streamer app folder.

If you have already isntalled the desktop recorder, uninstall that at this point.

Now reboot your system

Now install (this release)[https://github.com/DevL0rd/SkyNX/releases/tag/v0.6]  It will automatically setup the drivers though if it doesn't work immediately for audio or the controller, do one more reboot.

Let me know how it goes :)

**Comment by skydark719** [comment]
Now it runs flawlessly, and my controllers works again without issues right now, thanks.

The command log now shows me that the homebrew apps runs at 38-40 fps at almost every moment, faster than before. Now runs with 0 stutters and without any lost of video signal (the audio seemes great now) :).
I highly recommend you to share this homebrew app to others on GBATemp or another popular forum to make people know the replacement of In-Home-Switching!

**Comment by DevL0rd** [comment]
@skydark719 
Will do! A few more releases down the line and we will have it at 60 hopefully XD

And I spose I am making a GBATemp account XD

**Comment by skydark719** [comment]
> 
> 
> @skydark719
> Will do! A few more releases down the line and we will have it at 60 hopefully XD
> 
> And I spose I am making a GBATemp account XD

Now I'm really running this at 60fps, it's totally awesome! :)

And I see that every plugged control in my Switch works connected to my PC playing every game with my Switch in the dock and off screen, and works even better than Bluetooth controllers.

That's really amazing if I want to play for example Super Mario Galaxy on Dolphin emulating Wii Motes with my JoyCon and without the hassle of desync and syncronice the controllers from my Switch, I don't know if the funcion of gyroscope is compatible with SkyNX.
