### ISSUE TITLE
Controller/Audio not working

### ISSUE THREAD

**Issue by KewlSokudo** [DevL0rd/SkyNX#71]
So I discovered this app just recently and when I decided to try it out, the streaming works great on my RTX 2060 but there is never any audio and it just spits "Could not plug in controller driver. Make sure the driver is installed." at the console every second. I've lost count of how many times I've had to restart my computer and try to install the controller/audio driver through the software. I've even uninstall the ScpDriverInterface. And to make matters worse, it freezes constantly which ends up disconnecting the Switch.

What could be wrong?

**Comment by jason76890** [comment]
i have the same problem
