### ISSUE TITLE
Software keeps closing

### ISSUE THREAD

**Issue by Androphonomania** [DevL0rd/SkyNX#81]
On the switch, whenever I open the app after I've installed it, it keeps "closing because an error occurred". I don't know how to fix this. I've tried fully rebooting my switch and reinstalling the nsp, but it still just closes when opened. Please help!

**Comment by vamidi** [comment]
happen to me as well I am running Atmosphere 19.3

**Comment by acejoker6** [comment]
I have the same problem after installing the SkyNX_Forwarder.nsp using Goldleaf. 

I did find that using Goldleaf to launch the .nro file instead does work though. To do so, navigate to your SD Card > Switch folder > SkyNX folder and launch the SkyNX.nro file instead. 

Bit inconvenient to get to, but at least it should work in letting you use the app.
