### ISSUE TITLE
Javascript errors and Incorrect data length

### ISSUE THREAD

**Issue by starfire213** [DevL0rd/SkyNX#86]
When the Streamer connects to the switch, it says it connected to switch, then just outputs a ton of 
`Incorrect Data Length 416 -00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040f9bd001869bf00c8ddbed2f2cabc3162773c38e857bd0100000000000000`
With each one having a different ending code, Running on a intel i3 Lenovo Laptop

The java script errors are this 
![image](https://user-images.githubusercontent.com/56050355/158482399-745702c6-2b0f-49fa-8556-0d0dce9acda2.png)
![image](https://user-images.githubusercontent.com/56050355/158482432-7e8bf136-fd7d-4aa8-a83a-f396bf9cce6c.png)

**Comment by starfire213** [comment]
Ok just fixed it by re extracting the zip file

**Comment by guillaumeoudin** [comment]
Same issue, re-extracting the zip file didn't solve this for me. Any clue ?
