### ISSUE TITLE
App black screens after launching on Switch, installed through Homebrew App Store

### ISSUE THREAD

**Issue by moshevo** [DevL0rd/SkyNX#9]
I'm using a 9.1.0 Switch with Atmosphere 10.1, and I installed the app through the Homebrew App Store
It shows up as an applet, and I can click the icon, but the app itself doesn't start fully.
My Switch doesn't crash and I can exit out with the home button but all I get is a black screen when I try to launch it.

**Comment by DevL0rd** [comment]
It works on everything thing else so it sounds like something on your end.

How long did you wait for it to start. I heard for a few people on 9.1.0 that it takes a minute on first run.

**Comment by moshevo** [comment]
I reset my Switch completely and the app worked instantly, egg on my face.
Thank you for the quick reply though

**Comment by DevL0rd** [comment]
haha np!
